require('dotenv').config();
const express=require('express');
const path=require('path');const fs=require('fs');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const multer=require('multer');const initSqlJs=require('sql.js');const pdfParse=require('pdf-parse');
const app=express();const PORT=process.env.PORT||4000;const JWT_SECRET=process.env.JWT_SECRET||'infra-pulse-change-me';
const DB_DIR=path.join(__dirname,'data');const DB_FILE=path.join(DB_DIR,'infrapulse.sqlite');let SQL=null;let db=null;
const upload=multer({dest:path.join(__dirname,'uploads'),limits:{fileSize:10*1024*1024}});
app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));
const cities=JSON.parse(fs.readFileSync(path.join(__dirname,'data/india-cities.json'),'utf8'));
const captchaStore=new Map();
const asyncH=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
function q(text,params=[]){
  const normalized=text.replace(/\bNOW\(\)/gi,'CURRENT_TIMESTAMP').replace(/\$([0-9]+)/g,(_,n)=>'?').replace(/\bFALSE\b/gi,'0').replace(/\bTRUE\b/gi,'1');
  const ordered=[]; text.replace(/\$([0-9]+)/g,(_,n)=>{ordered.push(params[Number(n)-1]); return _;});
  const stmt=db.prepare(normalized);
  try { stmt.bind(ordered); const rows=[]; while(stmt.step()) rows.push(stmt.getAsObject()); const changes=db.getRowsModified(); if(/^(SELECT|WITH|PRAGMA)/i.test(normalized.trim())) return Promise.resolve({rows}); dbSave(); return Promise.resolve({rows,changes,rowCount:changes}); } finally { stmt.free(); }
}
function dbSave(){fs.mkdirSync(DB_DIR,{recursive:true});fs.writeFileSync(DB_FILE,Buffer.from(db.export()));}
async function initDb(){
  fs.mkdirSync(DB_DIR,{recursive:true});
  SQL=await initSqlJs({locateFile:file=>path.join(__dirname,'node_modules','sql.js','dist',file)});
  db=fs.existsSync(DB_FILE)?new SQL.Database(new Uint8Array(fs.readFileSync(DB_FILE))):new SQL.Database();
  db.run(fs.readFileSync(path.join(__dirname,'sql/schema.sql'),'utf8')); dbSave();
  console.log('SQLite database ready:',DB_FILE);
}
function tokenFor(user){return jwt.sign({id:user.id,email:user.email,username:user.username},JWT_SECRET,{expiresIn:'7d'})}
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});const p=jwt.verify(h.slice(7),JWT_SECRET);const r=await q('SELECT id,full_name,username,email,phone,company,department,role,preferred_language,theme,created_at FROM users WHERE id=$1',[p.id]);if(!r.rows[0])return res.status(401).json({error:'User not found'});req.user=r.rows[0];next()}catch(e){res.status(401).json({error:'Invalid or expired session'})}}
function validPassword(p){return typeof p==='string'&&p.length>=8&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p)}
app.get('/api/health',asyncH(async(req,res)=>{const r=await q('SELECT NOW() AS now');res.json({ok:true,service:'Infra-Pulse',database:'sqlite',time:r.rows[0].now})}));
app.get('/api/db-status',async(req,res)=>{try{const r=await q("SELECT 'infrapulse.sqlite' AS database, CURRENT_TIMESTAMP AS now");res.json({ok:true,database:r.rows[0].database,time:r.rows[0].now})}catch(e){res.status(503).json({ok:false,error:'Local SQLite database is not available.'})}});
app.get('/api/captcha',(req,res)=>{const key=Math.random().toString(36).slice(2)+Date.now();const a=Math.floor(Math.random()*9)+1,b=Math.floor(Math.random()*9)+1;captchaStore.set(key,{answer:String(a+b),expires:Date.now()+5*60*1000});res.json({key,question:`What is ${a} + ${b}?`})});
app.get('/api/cities',(req,res)=>{const term=String(req.query.q||'').trim().toLowerCase();res.json(term?cities.filter(x=>(x.city+' '+x.state).toLowerCase().includes(term)).slice(0,12):cities.slice(0,12))});
app.post('/api/auth/register',asyncH(async(req,res)=>{const {full_name,username,email,password,phone,company,department,role='Project Manager',preferred_language='en',captchaKey,captchaAnswer}=req.body;
 const cap=captchaStore.get(captchaKey); if(!cap||cap.expires<Date.now()||String(captchaAnswer||'').trim()!==cap.answer){return res.status(400).json({error:'CAPTCHA answer is incorrect or expired.'})} captchaStore.delete(captchaKey);if(!full_name||!username||!email||!validPassword(password))return res.status(400).json({error:'Name, username, email and a strong password are required. Password needs 8+ characters with uppercase, lowercase, number and special character.'});const r=await q('SELECT id FROM users WHERE lower(email)=lower($1) OR lower(username)=lower($2)',[email.trim(),username.trim()]);if(r.rows.length)return res.status(409).json({error:'Email or username is already registered.'});const hash=await bcrypt.hash(password,12);const u=await q(`INSERT INTO users(full_name,username,email,password_hash,phone,company,department,role,preferred_language) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,full_name,username,email,phone,company,department,role,preferred_language,theme,created_at`,[full_name.trim(),username.trim(),email.trim().toLowerCase(),hash,phone||null,company||null,department||null,role,preferred_language]);res.status(201).json({token:tokenFor(u.rows[0]),user:u.rows[0]})}));
app.post('/api/auth/login',asyncH(async(req,res)=>{const {identifier,password,captchaKey,captchaAnswer}=req.body;if(!identifier||!password)return res.status(400).json({error:'Username/email and password are required.'});const cap=captchaStore.get(captchaKey);if(!cap||cap.expires<Date.now()||String(captchaAnswer||'').trim()!==cap.answer)return res.status(400).json({error:'CAPTCHA answer is incorrect or expired.'});captchaStore.delete(captchaKey);const r=await q('SELECT * FROM users WHERE lower(username)=lower($1) OR lower(email)=lower($1)',[identifier.trim()]);if(!r.rows[0]||!(await bcrypt.compare(password,r.rows[0].password_hash)))return res.status(401).json({error:'Invalid username/email or password.'});const u=r.rows[0];delete u.password_hash;res.json({token:tokenFor(u),user:u})}));
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}));
app.patch('/api/auth/me',auth,asyncH(async(req,res)=>{const {full_name,phone,company,department,preferred_language,theme}=req.body;const r=await q(`UPDATE users SET full_name=COALESCE($1,full_name),phone=COALESCE($2,phone),company=COALESCE($3,company),department=COALESCE($4,department),preferred_language=COALESCE($5,preferred_language),theme=COALESCE($6,theme),updated_at=NOW() WHERE id=$7 RETURNING id,full_name,username,email,phone,company,department,role,preferred_language,theme,created_at`,[full_name,phone,company,department,preferred_language,theme,req.user.id]);res.json({user:r.rows[0]})}));
app.post('/api/auth/change-password',auth,asyncH(async(req,res)=>{const {currentPassword,newPassword}=req.body;if(!validPassword(newPassword))return res.status(400).json({error:'New password does not meet password rules.'});const r=await q('SELECT password_hash FROM users WHERE id=$1',[req.user.id]);if(!(await bcrypt.compare(currentPassword,r.rows[0].password_hash)))return res.status(400).json({error:'Current password is incorrect.'});await q('UPDATE users SET password_hash=$1,updated_at=NOW() WHERE id=$2',[await bcrypt.hash(newPassword,12),req.user.id]);res.json({ok:true})}));
async function userProject(id,pid){const r=await q('SELECT * FROM projects WHERE id=$1 AND owner_id=$2',[pid,id]);return r.rows[0]}
app.get('/api/dashboard',auth,asyncH(async(req,res)=>{const [p,a,rpt,al]=await Promise.all([q('SELECT * FROM projects WHERE owner_id=$1 ORDER BY updated_at DESC',[req.user.id]),q(`SELECT a.*,p.name project_name FROM activities a JOIN projects p ON p.id=a.project_id WHERE p.owner_id=$1 ORDER BY a.planned_end IS NULL, a.planned_end`,[req.user.id]),q(`SELECT r.*,a.code activity_code,p.name project_name FROM reports r LEFT JOIN activities a ON a.id=r.activity_id LEFT JOIN projects p ON p.id=r.project_id WHERE r.owner_id=$1 ORDER BY r.created_at DESC LIMIT 8`,[req.user.id]),q(`SELECT al.*,a.code activity_code,p.name project_name FROM alerts al LEFT JOIN activities a ON a.id=al.activity_id LEFT JOIN projects p ON p.id=al.project_id WHERE al.owner_id=$1 AND al.resolved=false ORDER BY al.created_at DESC`,[req.user.id])]);const acts=a.rows;const total=acts.length,completed=acts.filter(x=>x.status==='Completed'||Number(x.actual_progress)>=100).length,delayed=acts.filter(x=>x.status==='Delayed'||Number(x.planned_progress)-Number(x.actual_progress)>=10).length,inprog=total-completed;const planned=total?acts.reduce((s,x)=>s+Number(x.planned_progress),0)/total:0;const actual=total?acts.reduce((s,x)=>s+Number(x.actual_progress),0)/total:0;res.json({projects:p.rows,activities:acts,reports:rpt.rows,alerts:al.rows,stats:{total,completed,in_progress:inprog,delayed,open_alerts:al.rows.length,planned:+planned.toFixed(1),actual:+actual.toFixed(1)}})}));
app.get('/api/projects',auth,asyncH(async(req,res)=>{const r=await q('SELECT * FROM projects WHERE owner_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json({projects:r.rows})}));
app.post('/api/projects',auth,asyncH(async(req,res)=>{const {name,client,location,state,start_date,end_date,planned_progress=0,actual_progress=0,status='In Progress'}=req.body;if(!name)return res.status(400).json({error:'Project name is required.'});const r=await q(`INSERT INTO projects(owner_id,name,client,location,state,start_date,end_date,planned_progress,actual_progress,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.user.id,name,client||null,location||null,state||null,start_date||null,end_date||null,planned_progress,actual_progress,status]);res.status(201).json({project:r.rows[0]})}));
app.put('/api/projects/:id',auth,asyncH(async(req,res)=>{const {name,client,location,state,start_date,end_date,planned_progress,actual_progress,status}=req.body;const r=await q(`UPDATE projects SET name=$1,client=$2,location=$3,state=$4,start_date=$5,end_date=$6,planned_progress=$7,actual_progress=$8,status=$9,updated_at=NOW() WHERE id=$10 AND owner_id=$11 RETURNING *`,[name,client||null,location||null,state||null,start_date||null,end_date||null,planned_progress||0,actual_progress||0,status||'In Progress',req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:'Project not found'});res.json({project:r.rows[0]})}));
app.delete('/api/projects/:id',auth,asyncH(async(req,res)=>{const r=await q('DELETE FROM projects WHERE id=$1 AND owner_id=$2 RETURNING id',[req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:'Project not found'});res.json({ok:true})}));
app.get('/api/projects/:id/activities',auth,asyncH(async(req,res)=>{if(!(await userProject(req.user.id,req.params.id)))return res.status(404).json({error:'Project not found'});const r=await q('SELECT * FROM activities WHERE project_id=$1 ORDER BY planned_end IS NULL, planned_end',[req.params.id]);res.json({activities:r.rows})}));
app.post('/api/activities',auth,asyncH(async(req,res)=>{const {project_id,code,name,planned_progress=0,actual_progress=0,planned_start,planned_end,status='In Progress'}=req.body;if(!(await userProject(req.user.id,project_id)))return res.status(404).json({error:'Project not found'});const r=await q(`INSERT INTO activities(project_id,code,name,planned_progress,actual_progress,planned_start,planned_end,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[project_id,code,name,planned_progress,actual_progress,planned_start||null,planned_end||null,status]);res.status(201).json({activity:r.rows[0]})}));
app.put('/api/activities/:id',auth,asyncH(async(req,res)=>{const {code,name,planned_progress,actual_progress,planned_start,planned_end,status}=req.body;const own=await q('SELECT a.id FROM activities a JOIN projects p ON p.id=a.project_id WHERE a.id=$1 AND p.owner_id=$2',[req.params.id,req.user.id]);if(!own.rows[0])return res.status(404).json({error:'Activity not found'});await q('UPDATE activities SET code=$1,name=$2,planned_progress=$3,actual_progress=$4,planned_start=$5,planned_end=$6,status=$7 WHERE id=$8',[code,name,planned_progress,actual_progress,planned_start||null,planned_end||null,status||'In Progress',req.params.id]);const r=await q('SELECT * FROM activities WHERE id=$1',[req.params.id]);res.json({activity:r.rows[0]})}));
app.delete('/api/activities/:id',auth,asyncH(async(req,res)=>{const own=await q('SELECT a.id FROM activities a JOIN projects p ON p.id=a.project_id WHERE a.id=$1 AND p.owner_id=$2',[req.params.id,req.user.id]);if(!own.rows[0])return res.status(404).json({error:'Activity not found'});await q('DELETE FROM activities WHERE id=$1',[req.params.id]);res.json({ok:true})}));
app.post('/api/reports',auth,asyncH(async(req,res)=>{const {project_id,activity_id,report_date,location_text,latitude,longitude,description,quantity,unit}=req.body;if(project_id&&!(await userProject(req.user.id,project_id)))return res.status(404).json({error:'Project not found'});let score=null;let source='database';if(activity_id){const ar=await q('SELECT a.* FROM activities a JOIN projects p ON p.id=a.project_id WHERE a.id=$1 AND p.owner_id=$2',[activity_id,req.user.id]);if(ar.rows[0]){const a=ar.rows[0];score=Math.max(0,Math.min(100,100-Math.abs(Number(a.planned_progress)-Number(a.actual_progress))*2));}}const r=await q(`INSERT INTO reports(owner_id,project_id,activity_id,report_date,location_text,latitude,longitude,description,quantity,unit,ai_match_score,match_source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,project_id||null,activity_id||null,report_date||new Date().toISOString().slice(0,10),location_text||null,latitude||null,longitude||null,description||null,quantity||null,unit||null,score,source]);res.status(201).json({report:r.rows[0],match:{score,source,explanation:score===null?'No activity selected; no match score was invented.':'Calculated from the selected database activity variance.'}})}));
app.get('/api/reports',auth,asyncH(async(req,res)=>{const r=await q(`SELECT r.*,p.name project_name,a.code activity_code,a.name activity_name FROM reports r LEFT JOIN projects p ON p.id=r.project_id LEFT JOIN activities a ON a.id=r.activity_id WHERE r.owner_id=$1 ORDER BY r.report_date DESC,r.created_at DESC`,[req.user.id]);res.json({reports:r.rows})}));
app.post('/api/documents/upload',auth,upload.single('file'),asyncH(async(req,res)=>{
  if(!req.file)return res.status(400).json({error:'File is required'});
  const ext=path.extname(req.file.originalname).toLowerCase();
  const allowed=['.txt','.csv','.pdf'];
  if(!allowed.includes(ext)){fs.unlink(req.file.path,()=>{});return res.status(400).json({error:'For reliable offline processing, upload CSV, TXT or PDF files.'})}
  let text=''; const buf=fs.readFileSync(req.file.path);
  try { if(ext==='.txt'||ext==='.csv') text=buf.toString('utf8'); else { const parsed=await pdfParse(buf); text=parsed.text||''; } }
  finally { fs.unlink(req.file.path,()=>{}); }
  if(!text.trim())return res.status(400).json({error:'No readable text was found in this document.'});
  const projectId=req.body.project_id||null;
  if(projectId&&!(await userProject(req.user.id,projectId)))return res.status(404).json({error:'Project not found'});
  const r=await q(`INSERT INTO documents(owner_id,project_id,original_name,mime_type,size_bytes,extracted_text,extracted_at) VALUES($1,$2,$3,$4,$5,$6,NOW()) RETURNING id,original_name,mime_type,size_bytes,project_id,extracted_text,created_at`,[req.user.id,projectId,req.file.originalname,req.file.mimetype,req.file.size,text]);
  const facts=extractDocumentFacts(text,ext);
  for(const f of facts) await q('INSERT INTO document_facts(document_id,owner_id,fact_type,payload_json,status) VALUES($1,$2,$3,$4,$5)',[r.rows[0].id,req.user.id,f.type,JSON.stringify(f.payload),'pending']);
  res.status(201).json({document:r.rows[0],facts,analysis:{characters:text.length,lines:text.split(/\r?\n/).filter(Boolean).length,fact_count:facts.length}})
}));

function cleanNum(v){const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null}
function extractDocumentFacts(text,ext){
  const facts=[]; const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const all=text.replace(/\r/g,'');
  let projectName=null;
  const pm=all.match(/(?:PROJECT|Project)\s*[:\-]\s*([^\n\r,]+)/i); if(pm) projectName=pm[1].trim();
  if(!projectName&&ext==='.csv'){
    const row=lines[1]||''; const first=(row.split(',')[1]||row.split(',')[0]||'').trim(); if(first)projectName=first;
  }
  if(projectName) facts.push({type:'project',payload:{name:projectName,planned_progress:cleanNum((all.match(/(?:Planned(?: Project)? Progress)\s*[:\-]\s*([0-9.]+)%?/i)||[])[1]),actual_progress:cleanNum((all.match(/(?:Actual(?: Project)? Progress)\s*[:\-]\s*([0-9.]+)%?/i)||[])[1]),status:(all.match(/(?:Project )?Status\s*[:\-]\s*([^\n\r]+)/i)||[])[1]?.trim()||'In Progress'}});
  const codeRe=/(?:ACTIVITY\s*\d*\s*)?Code\s*[:\-]\s*([A-Za-z0-9_-]+)[\s\S]{0,350}?Name\s*[:\-]\s*([^\n\r]+)[\s\S]{0,500}?Planned Progress\s*[:\-]\s*([0-9.]+)%[\s\S]{0,250}?Actual Progress\s*[:\-]\s*([0-9.]+)%/gi;
  let m; while((m=codeRe.exec(all))){ const chunk=m[0]; const status=(chunk.match(/Status\s*[:\-]\s*([^\n\r]+)/i)||[])[1]?.trim()||((cleanNum(m[3])-cleanNum(m[4])>=10)?'Delayed':'In Progress'); const ps=(chunk.match(/Planned Start\s*[:\-]\s*([^\n\r]+)/i)||[])[1]?.trim()||null; const pe=(chunk.match(/Planned End\s*[:\-]\s*([^\n\r]+)/i)||[])[1]?.trim()||null; facts.push({type:'activity',payload:{project_name:projectName,code:m[1].trim(),name:m[2].trim(),planned_progress:cleanNum(m[3]),actual_progress:cleanNum(m[4]),status,planned_start:ps,planned_end:pe}}); }
  if(ext==='.csv'){
    const rows=lines.map(l=>l.split(',').map(v=>v.trim())); const header=rows[0]?.map(h=>h.toLowerCase());
    const idx=(...names)=>names.map(n=>header?.indexOf(n)).find(i=>i>=0);
    const ip=idx('project','project_name'), ic=idx('activity_code','code'), ina=idx('activity','activity_name','name'), ipl=idx('planned_progress'), ia=idx('actual_progress'), ist=idx('status'), ips=idx('planned_start'), ipe=idx('planned_end');
    for(const row of rows.slice(1)){ if(!row.length)continue; const pn=ip!=null?row[ip]:projectName, code=ic!=null?row[ic]:null, name=ina!=null?row[ina]:null; if(code&&name)facts.push({type:'activity',payload:{project_name:pn,code,name,planned_progress:ipl!=null?cleanNum(row[ipl]):0,actual_progress:ia!=null?cleanNum(row[ia]):0,status:ist!=null&&row[ist]?row[ist]:'In Progress',planned_start:ips!=null?row[ips]||null:null,planned_end:ipe!=null?row[ipe]||null:null}}); }
  }
  const mat=all.match(/(?:Steel Pipe|Material)[^\n\r]*?(?:Availability|Available)[^0-9]*([0-9.]+)%[^\n\r]*?(?:Required)[^0-9]*([0-9.]+)%/i); if(mat)facts.push({type:'resource',payload:{project_name:projectName,resource:'Material availability',available:cleanNum(mat[1]),required:cleanNum(mat[2])}});
  const wf=all.match(/(?:Previous Workforce|Previous workers)\s*[:\-]\s*([0-9.]+)[\s\S]{0,80}?(?:Current Workforce|Current workers)\s*[:\-]\s*([0-9.]+)/i); if(wf)facts.push({type:'resource',payload:{project_name:projectName,resource:'Workforce',previous:cleanNum(wf[1]),current:cleanNum(wf[2])}});
  if(!facts.length)facts.push({type:'note',payload:{text:all.slice(0,1200)}});
  return facts;
}
async function resolveProjectForFact(ownerId,payload,documentProjectId){
  if(documentProjectId){const p=await userProject(ownerId,documentProjectId);if(p)return p;}
  if(payload.project_name){const r=await q('SELECT * FROM projects WHERE owner_id=$1 AND lower(name)=lower($2) LIMIT 1',[ownerId,payload.project_name]);if(r.rows[0])return r.rows[0];}
  return null;
}
async function refreshRiskAlerts(ownerId,projectId){
  const projects=projectId?[await userProject(ownerId,projectId)]:((await q('SELECT * FROM projects WHERE owner_id=$1',[ownerId])).rows);
  for(const p of projects.filter(Boolean)){
    const ar=await q('SELECT * FROM activities WHERE project_id=$1',[p.id]);
    const risks=[];
    const pv=Number(p.planned_progress)-Number(p.actual_progress); if(pv>=10)risks.push({type:'schedule',severity:pv>=20?'high':'medium',title:`${p.name} · Project behind plan`,message:`Actual progress ${p.actual_progress}% is ${pv.toFixed(1)} points below planned ${p.planned_progress}%.`});
    for(const a of ar.rows){const v=Number(a.planned_progress)-Number(a.actual_progress);if(a.status==='Delayed'||v>=10)risks.push({type:'activity',severity:v>=20?'high':'medium',title:`${a.code} · ${a.name}`,message:`Actual ${a.actual_progress}% vs planned ${a.planned_progress}% (${v.toFixed(1)} point variance).`});}
    const docs=await q('SELECT extracted_text FROM documents WHERE owner_id=$1 AND project_id=$2 ORDER BY created_at DESC LIMIT 5',[ownerId,p.id]);let joined=docs.rows.map(x=>x.extracted_text||'').join('\n');const mm=joined.match(/(?:Steel Pipe|Material)[^\n\r]*?(?:Availability|Available)[^0-9]*([0-9.]+)%[^\n\r]*?(?:Required)[^0-9]*([0-9.]+)%/i);if(mm&&Number(mm[1])<Number(mm[2]))risks.push({type:'resource',severity:'high',title:`${p.name} · Material shortage`,message:`Material availability is ${mm[1]}% while ${mm[2]}% is required, based on uploaded project documents.`});
    for(const risk of risks){const ex=await q('SELECT id FROM alerts WHERE owner_id=$1 AND project_id=$2 AND title=$3 AND resolved=0 LIMIT 1',[ownerId,p.id,risk.title]);if(!ex.rows[0])await q('INSERT INTO alerts(owner_id,project_id,type,severity,title,message) VALUES($1,$2,$3,$4,$5,$6)',[ownerId,p.id,risk.type,risk.severity,risk.title,risk.message]);}
  }
}
app.get('/api/documents/:id/facts',auth,asyncH(async(req,res)=>{const d=await q('SELECT * FROM documents WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.id]);if(!d.rows[0])return res.status(404).json({error:'Document not found'});const f=await q('SELECT id,fact_type,payload_json,status,created_at FROM document_facts WHERE document_id=$1 AND owner_id=$2 ORDER BY id',[req.params.id,req.user.id]);res.json({document:d.rows[0],facts:f.rows.map(x=>({...x,payload:JSON.parse(x.payload_json)}))})}));
app.post('/api/documents/:id/apply',auth,asyncH(async(req,res)=>{const d=await q('SELECT * FROM documents WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.id]);if(!d.rows[0])return res.status(404).json({error:'Document not found'});const ids=Array.isArray(req.body.fact_ids)?req.body.fact_ids:null;const f=await q(`SELECT * FROM document_facts WHERE document_id=$1 AND owner_id=$2 AND status='pending'${ids?' AND id IN ('+ids.map(()=>'?').join(',')+')':''}`,[req.params.id,req.user.id,...(ids||[])]);let applied=0,createdProjects=0,updatedActivities=0;let targetProjectId=d.rows[0].project_id||null;
  for(const row of f.rows){const payload=JSON.parse(row.payload_json); if(row.fact_type==='project'){let p=await resolveProjectForFact(req.user.id,payload,targetProjectId);if(!p){const n=await q(`INSERT INTO projects(owner_id,name,planned_progress,actual_progress,status) VALUES($1,$2,$3,$4,$5) RETURNING *`,[req.user.id,payload.name,payload.planned_progress||0,payload.actual_progress||0,payload.status||'In Progress']);p=n.rows[0];createdProjects++;}else{await q('UPDATE projects SET planned_progress=$1,actual_progress=$2,status=$3,updated_at=NOW() WHERE id=$4 AND owner_id=$5',[payload.planned_progress??p.planned_progress,payload.actual_progress??p.actual_progress,payload.status||p.status,p.id,req.user.id]);}targetProjectId=p.id;}
    else if(row.fact_type==='activity'){const p=await resolveProjectForFact(req.user.id,payload,targetProjectId);if(!p)continue;let a=await q('SELECT * FROM activities WHERE project_id=$1 AND code=$2',[p.id,payload.code]);if(a.rows[0]){await q('UPDATE activities SET name=$1,planned_progress=$2,actual_progress=$3,status=$4,planned_start=$5,planned_end=$6 WHERE id=$7',[payload.name,payload.planned_progress??0,payload.actual_progress??0,payload.status||'In Progress',payload.planned_start||null,payload.planned_end||null,a.rows[0].id]);updatedActivities++;}else{await q('INSERT INTO activities(project_id,code,name,planned_progress,actual_progress,status,planned_start,planned_end) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[p.id,payload.code,payload.name,payload.planned_progress??0,payload.actual_progress??0,payload.status||'In Progress',payload.planned_start||null,payload.planned_end||null]);updatedActivities++;}}
    await q('UPDATE document_facts SET status=\'accepted\' WHERE id=$1 AND owner_id=$2',[row.id,req.user.id]);applied++; }
  if(targetProjectId)await q('UPDATE documents SET project_id=$1 WHERE id=$2 AND owner_id=$3',[targetProjectId,req.params.id,req.user.id]); await refreshRiskAlerts(req.user.id,targetProjectId); res.json({ok:true,applied,createdProjects,updatedActivities});
}));
app.post('/api/documents/:id/reject',auth,asyncH(async(req,res)=>{const ids=Array.isArray(req.body.fact_ids)?req.body.fact_ids:[];if(!ids.length)return res.status(400).json({error:'fact_ids required'});let rejected=0;for(const id of ids){const r=await q("UPDATE document_facts SET status='rejected' WHERE owner_id=$1 AND document_id=$2 AND id=$3 AND status='pending'",[req.user.id,req.params.id,id]);rejected+=r.changes||0;}res.json({ok:true,rejected})}));
app.get('/api/risk-radar',auth,asyncH(async(req,res)=>{await refreshRiskAlerts(req.user.id,req.query.project_id||null);const p=await q('SELECT * FROM projects WHERE owner_id=$1 ORDER BY updated_at DESC',[req.user.id]);const result=[];for(const x of p.rows){const a=await q('SELECT * FROM activities WHERE project_id=$1',[x.id]);const risks=[];const variance=Number(x.planned_progress)-Number(x.actual_progress);if(variance>0)risks.push({severity:variance>=15?'high':'medium',title:'Schedule variance',detail:`${variance.toFixed(1)} percentage points behind plan.`});for(const z of a.rows){const v=Number(z.planned_progress)-Number(z.actual_progress);if(z.status==='Delayed'||v>=10)risks.push({severity:v>=20?'high':'medium',title:z.name,detail:`${z.actual_progress}% actual vs ${z.planned_progress}% planned.`});}result.push({project:x,health:risks.some(r=>r.severity==='high')?'High':risks.length?'Medium':'Low',risks})}res.json({projects:result})}));
app.get('/api/schedule',auth,asyncH(async(req,res)=>{if(req.query.project_id&&!(await userProject(req.user.id,req.query.project_id)))return res.status(404).json({error:'Project not found'});const r=await q(`SELECT a.*,p.name project_name FROM activities a JOIN projects p ON p.id=a.project_id WHERE p.owner_id=$1 ${req.query.project_id?'AND p.id=$2':''} ORDER BY a.planned_start IS NULL,a.planned_start,a.planned_end`,req.query.project_id?[req.user.id,req.query.project_id]:[req.user.id]);res.json({activities:r.rows})}));

app.get('/api/documents',auth,asyncH(async(req,res)=>{const r=await q('SELECT id,original_name,mime_type,size_bytes,project_id,created_at,extracted_at FROM documents WHERE owner_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json({documents:r.rows})}));
app.get('/api/alerts',auth,asyncH(async(req,res)=>{const r=await q(`SELECT al.*,p.name project_name,a.code activity_code FROM alerts al LEFT JOIN projects p ON p.id=al.project_id LEFT JOIN activities a ON a.id=al.activity_id WHERE al.owner_id=$1 ORDER BY al.resolved,al.created_at DESC`,[req.user.id]);res.json({alerts:r.rows})}));
app.patch('/api/alerts/:id',auth,asyncH(async(req,res)=>{const r=await q('UPDATE alerts SET resolved=$1 WHERE id=$2 AND owner_id=$3 RETURNING *',[!!req.body.resolved,req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:'Alert not found'});res.json({alert:r.rows[0]})}));
app.get('/api/users',auth,asyncH(async(req,res)=>{const r=await q(`SELECT id,full_name,username,email,phone,company,department,role,preferred_language,theme,created_at FROM users WHERE id=$1 ORDER BY created_at DESC`,[req.user.id]);res.json({users:r.rows})}));
app.get('/api/search',auth,asyncH(async(req,res)=>{const term='%'+String(req.query.q||'').trim()+'%';if(term==='%%')return res.json({results:[]});const [p,a,rpt,d,al]=await Promise.all([q('SELECT id,name,location,status FROM projects WHERE owner_id=$1 AND (name LIKE $2 OR location LIKE $2 OR client LIKE $2) LIMIT 20',[req.user.id,term]),q(`SELECT a.id,a.code,a.name,a.status,p.name project_name FROM activities a JOIN projects p ON p.id=a.project_id WHERE p.owner_id=$1 AND (a.code LIKE $2 OR a.name LIKE $2) LIMIT 20`,[req.user.id,term]),q(`SELECT r.id,r.report_date,r.description,p.name project_name,a.code activity_code FROM reports r LEFT JOIN projects p ON p.id=r.project_id LEFT JOIN activities a ON a.id=r.activity_id WHERE r.owner_id=$1 AND (r.description LIKE $2 OR r.location_text LIKE $2 OR a.code LIKE $2) LIMIT 20`,[req.user.id,term]),q('SELECT id,original_name FROM documents WHERE owner_id=$1 AND original_name LIKE $2 LIMIT 20',[req.user.id,term]),q('SELECT id,title,message,severity,resolved FROM alerts WHERE owner_id=$1 AND (title LIKE $2 OR message LIKE $2) LIMIT 20',[req.user.id,term])]);res.json({results:[...p.rows.map(x=>({...x,type:'project'})),...a.rows.map(x=>({...x,type:'activity'})),...rpt.rows.map(x=>({...x,type:'report'})),...d.rows.map(x=>({...x,type:'document'})),...al.rows.map(x=>({...x,type:'alert'}))]})}));
function bilingualSummary(lang,s){return lang==='hi'?`आपके डेटाबेस में ${s.total} activities हैं। ${s.completed} completed, ${s.in_progress} in progress और ${s.delayed} delayed हैं। औसत planned progress ${s.planned}% और actual progress ${s.actual}% है।`:`Your database contains ${s.total} activities: ${s.completed} completed, ${s.in_progress} in progress and ${s.delayed} delayed. Average planned progress is ${s.planned}% and actual progress is ${s.actual}%.`}
app.get('/api/ai/history',auth,asyncH(async(req,res)=>{const r=await q('SELECT id,role,content,language,created_at FROM chat_messages WHERE owner_id=$1 ORDER BY created_at ASC',[req.user.id]);res.json({messages:r.rows})}));
app.post('/api/ai/chat',auth,asyncH(async(req,res)=>{
 const question=String(req.body.question||'').trim(); const lang=req.body.language==='hi'?'hi':'en'; if(!question)return res.status(400).json({error:'Question required'});
 const ql=question.toLowerCase();
 const [projects,acts,alerts,reports,docs]=await Promise.all([
   q('SELECT * FROM projects WHERE owner_id=$1 ORDER BY updated_at DESC',[req.user.id]),
   q('SELECT a.*,p.name project_name,p.location,p.state FROM activities a JOIN projects p ON p.id=a.project_id WHERE p.owner_id=$1 ORDER BY a.planned_end IS NULL,a.planned_end',[req.user.id]),
   q('SELECT * FROM alerts WHERE owner_id=$1 AND resolved=0 ORDER BY created_at DESC',[req.user.id]),
   q('SELECT r.*,p.name project_name,a.code activity_code FROM reports r LEFT JOIN projects p ON p.id=r.project_id LEFT JOIN activities a ON a.id=r.activity_id WHERE r.owner_id=$1 ORDER BY r.report_date DESC LIMIT 20',[req.user.id]),
   q('SELECT id,original_name,project_id,extracted_text,created_at FROM documents WHERE owner_id=$1 ORDER BY created_at DESC LIMIT 10',[req.user.id])
 ]);
 let selectedProjects=projects.rows, selectedActs=acts.rows;
 const loc=(question.match(/(?:in|at|from)\s+([A-Za-z][A-Za-z ]+)/i)||[])[1]?.trim(); if(loc)selectedProjects=selectedProjects.filter(p=>(p.name+' '+(p.location||'')+' '+(p.state||'')).toLowerCase().includes(loc.toLowerCase()));
 for(const p of projects.rows){if(ql.includes(p.name.toLowerCase())){selectedProjects=[p];selectedActs=acts.rows.filter(a=>a.project_id===p.id);break}}
 if(/delayed|delay|behind|late|देरी|पीछे/.test(ql)) selectedActs=selectedActs.filter(a=>a.status==='Delayed'||Number(a.planned_progress)-Number(a.actual_progress)>=10);
 if(/incomplete|in progress|अधूर|चल/.test(ql)) selectedActs=selectedActs.filter(a=>Number(a.actual_progress)<100);
 let answer='',evidence=[];
 if(/why|reason|क्यों|कारण/.test(ql)){
   const p=selectedProjects[0]; if(!p){answer=lang==='hi'?'इस प्रश्न के लिए आपके डेटाबेस में कोई project नहीं मिला।':'No matching project was found in your database.'}
   else {const pa=acts.rows.filter(a=>a.project_id===p.id).filter(a=>a.status==='Delayed'||Number(a.planned_progress)-Number(a.actual_progress)>=10);const variance=Number(p.planned_progress)-Number(p.actual_progress);const relReports=reports.rows.filter(r=>r.project_id===p.id).slice(0,5);answer=lang==='hi'?`${p.name} की current progress ${p.actual_progress}% है जबकि planned ${p.planned_progress}% है; variance ${variance.toFixed(1)} points है। ${pa.length?`मुख्य delayed activities: ${pa.map(a=>a.name+' ('+a.actual_progress+'% actual / '+a.planned_progress+'% planned)').join(', ')}।`:''} ${relReports.length?'हाल की reports में '+relReports.map(r=>r.description).filter(Boolean).join(' | '):'इस project के लिए हाल की report उपलब्ध नहीं है।'}`:`${p.name} is at ${p.actual_progress}% actual versus ${p.planned_progress}% planned, a ${variance.toFixed(1)} point variance. ${pa.length?`Delayed activities: ${pa.map(a=>a.name+' ('+a.actual_progress+'% actual / '+a.planned_progress+'% planned)').join(', ')}. `:''}${relReports.length?'Recent reports: '+relReports.map(r=>r.description).filter(Boolean).join(' | '):'No recent report is stored for this project.'}`;evidence=[...pa.slice(0,5).map(a=>`Activity ${a.code}`),...relReports.slice(0,3).map(r=>`Daily report ${r.report_date}`)];}
 } else if(/project|projects|portfolio|प्रोजेक्ट/.test(ql)){answer=lang==='hi'?`आपके database में ${selectedProjects.length} projects हैं:\n`+selectedProjects.map((p,i)=>`${i+1}. ${p.name} — ${p.actual_progress}% actual / ${p.planned_progress}% planned`).join('\n'):`Your database contains ${selectedProjects.length} matching projects:\n`+selectedProjects.map((p,i)=>`${i+1}. ${p.name} — ${p.actual_progress}% actual / ${p.planned_progress}% planned`).join('\n');evidence=selectedProjects.map(p=>`Project ${p.name}`)}
 else if(/activity|activities|delayed|delay|incomplete|गतिविध|देरी/.test(ql)){answer=lang==='hi'?`Database से ${selectedActs.length} matching activities मिलीं:\n`+selectedActs.map((a,i)=>`${i+1}. ${a.code} · ${a.name} — ${a.actual_progress}% actual / ${a.planned_progress}% planned · ${a.status}`).join('\n'):`The database returned ${selectedActs.length} matching activities:\n`+selectedActs.map((a,i)=>`${i+1}. ${a.code} · ${a.name} — ${a.actual_progress}% actual / ${a.planned_progress}% planned · ${a.status}`).join('\n');evidence=selectedActs.slice(0,8).map(a=>`Activity ${a.code}`)}
 else if(/alert|risk|जोखिम|अलर्ट/.test(ql)){answer=lang==='hi'?`Database में ${alerts.rows.length} open alerts हैं:\n`+alerts.rows.map((a,i)=>`${i+1}. ${a.title} — ${a.message}`).join('\n'):`There are ${alerts.rows.length} open database alerts:\n`+alerts.rows.map((a,i)=>`${i+1}. ${a.title} — ${a.message}`).join('\n');evidence=alerts.rows.map(a=>`Alert ${a.title}`)}
 else if(/document|file|pdf|csv|txt|दस्तावेज|फाइल/.test(ql)){answer=docs.rows.length?(lang==='hi'?`आपके ${docs.rows.length} stored documents हैं: ${docs.rows.map(d=>d.original_name).join(', ')}। नवीनतम document का extracted content database में stored है।`:`You have ${docs.rows.length} stored documents: ${docs.rows.map(d=>d.original_name).join(', ')}. Their extracted content is stored in the database.`):(lang==='hi'?'अभी कोई document database में नहीं है।':'No documents are stored in your database yet.');evidence=docs.map(d=>`Document ${d.original_name}`)}
 else {const total=acts.rows.length,completed=acts.rows.filter(a=>Number(a.actual_progress)>=100||a.status==='Completed').length;answer=lang==='hi'?`आपके database में ${projects.rows.length} projects, ${total} activities, ${completed} completed activities और ${alerts.rows.length} open alerts हैं। मैं केवल आपके stored database records और uploaded document content पर आधारित उत्तर देता हूँ।`:`Your database contains ${projects.rows.length} projects, ${total} activities, ${completed} completed activities and ${alerts.rows.length} open alerts. This agent answers only from your stored database records and uploaded document content.`;}
 await q('INSERT INTO chat_messages(owner_id,role,content,language) VALUES($1,$2,$3,$4),($1,$5,$6,$4)',[req.user.id,'user',question,lang,'assistant',answer]);res.json({answer,evidence,source:'SQLite database only',facts:{projects:selectedProjects.length,activities:selectedActs.length,open_alerts:alerts.rows.length,documents:docs.rows.length}})
}));

app.post('/api/demo/import-test-data',auth,asyncH(async(req,res)=>{const existing=await q('SELECT id FROM projects WHERE owner_id=$1 LIMIT 1',[req.user.id]);if(existing.rows.length)return res.status(409).json({error:'Your account already has project data. Test import is allowed only for an empty account.'});const p1=await q(`INSERT INTO projects(owner_id,name,client,location,state,start_date,end_date,planned_progress,actual_progress,status) VALUES($1,'Assam Pipeline Expansion','Oil India Limited','Duliajan','Assam','2026-01-05','2026-12-20',62,55,'In Progress') RETURNING id`,[req.user.id]);const p2=await q(`INSERT INTO projects(owner_id,name,client,location,state,start_date,end_date,planned_progress,actual_progress,status) VALUES($1,'Jorhat Compressor Station','Oil India Limited','Jorhat','Assam','2026-03-01','2026-11-30',44,36,'In Progress') RETURNING id`,[req.user.id]);await q(`INSERT INTO activities(project_id,code,name,planned_progress,actual_progress,status) VALUES($1,'PIPE-1056','Excavation Section A',100,96,'In Progress'),($1,'CIV-2041','Foundation Concrete',62,38,'Delayed'),($2,'PIPE-3056','Pipeline Laying',55,45,'In Progress')`,[p1.rows[0].id]);const a=await q(`SELECT a.id FROM activities a JOIN projects p ON p.id=a.project_id WHERE p.owner_id=$1 AND a.code='CIV-2041'`,[req.user.id]);await q(`INSERT INTO alerts(owner_id,project_id,activity_id,type,severity,title,message) VALUES($1,$2,$3,'Schedule Delay','high','CIV-2041 · Schedule Delay','Actual progress is 24 percentage points behind plan.')`,[req.user.id,p1.rows[0].id,a.rows[0].id]);res.json({ok:true,message:'Sample project data imported into your own account.'})}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:err.message||'Server error'})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
process.on('SIGINT',()=>{try{dbSave()}finally{process.exit(0)}});
process.on('SIGTERM',()=>{try{dbSave()}finally{process.exit(0)}});
initDb().then(()=>app.listen(PORT,()=>console.log(`Infra-Pulse running at http://localhost:${PORT}`))).catch(err=>{console.error('SQLite initialization failed.');console.error(err.message);console.error('Delete data/infrapulse.sqlite if you need a fresh local database, then restart.');process.exit(1)});
